### ISSUE TITLE
Logstarstream verfügbar machen

### ISSUE THREAD

**Issue by specka** [zalf-rdm/Logstar-online-Stream#16]
Aus Redmine übernommen: https://redmine.bonares.de/issues/3040 
Logstarstream zusammen mit dem Grafana Dashboard innerhalb des Zalfnetzwerkes aufsetzen und für patchcrop bereitstellen?
ggf. als erstes Testprojekt in einer Kubernetes Umgebung

**Comment by mwallschlaeger** [comment]
ist im amumu cluster verfügbar unter grafana.amumu.bonares.de
